name: NoTP
main: awzaw\notp\Main
version: 1.0.7
api: [3.0.0]
load: POSTWORLD
author: awzaw
website: https://github.com/awzaw
commands:
 notp:
  description: "Toggles TP Accept mode for yourself"
  usage: "/notp"
  permission: notp.toggle
permissions:
  notp:
    description: "Allows access to all NoTP features"
    default: op
    children:
      notp.toggle:
        description: "Allows the player to toggle NoTP mode"
        default: false
        children:
          notp.toggle.self:
            description: "Allows the player to toggle NoTP mode for themselves"
            default: false
